### ISSUE TITLE
The app is a little bit not intuitive because the are dots with colours and numbers and leafes and loud speakers shown etc.

### ISSUE THREAD

**Issue by GertS** [GertS/VindDeRust#10]

**Comment by codehub-rony** [comment]
A possible fix is to link the different parameters for 'rust' to the appearance of one marker per location instead of having 3 (overlapping) markers. For example,  the existence of a marker means a bench is available. The size of the marker will indicate the amount of 'green'. The color of the marker can represent the sound disturbance. Clustering of Markers can be based on these new markers.

**Comment by GertS** [comment]
This is indeed the best solution, but however I think it is too complicated to implement it before the deadline. Unless you see a good and easy way to do this.

**Comment by codehub-rony** [comment]
I think I have an idea. Will try to fix it tomorrow
